name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.9
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo-no-background.png
  image_dark: assets/images/logo-no-background.png

  android_12:
    icon_background_color: "#f7f6f1"
    icon_background_color_dark: "#272727"
    image: assets/images/logo-no-background.png
    image_dark: assets/images/logo-no-background.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/